@url=http://localhost:5137
@hostId=1
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkRpZWdvIiwiZmFtaWx5X25hbWUiOiJHb21leiIsImp0aSI6IjllZjdhZDhkLWYxNGMtNDQwNi04MDZjLWEyNDEyNTAzZjZkOSIsImV4cCI6MTc3NDg5NTY4MiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.Kfi-jSlx_DkGe78m4C0LKZTUXlzfjiqw2o9cVPWw1DU

###

POST {{url}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "YummyMenu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}

###