<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5a00a369-e167-4081-84d3-16af67a42d7c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportGym.Contracts\SportGym.Contracts.csproj" />
    <ProjectReference Include="..\SportGym.Application\SportGym.Application.csproj" />
    <ProjectReference Include="..\SportGym.Infrastructure\SportGym.Infrastructure.csproj" />
  </ItemGroup>

</Project>
